name: Build and deploy Next.js app to Azure Web App - prateek-portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install --force

      - name: Build app
        run: npm run build

      - name: Copy necessary files for deployment
        run: |
          mkdir deploy
          cp -r .next public package.json node_modules deploy/
          echo '{}' > deploy/.env.production.local # Or your real env vars

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4534393C9DAB4EC6A349C30F8F7C40E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2AF5FE41726C4D5CAE805A27E5BB866A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DFCEAF7C40494826A2118AF4E95C2C35 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prateek-portfolio'
          slot-name: 'Production'
          package: .
