name: Build and deploy Node.js app to Azure Web App - prateek-portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install --force

      - name: Build Next.js
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir deploy
          cp -r .next public package.json node_modules deploy/
          cp -r next.config.js deploy/ || true
          cp -r ecosystem.config.js deploy/ || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4534393C9DAB4EC6A349C30F8F7C40E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2AF5FE41726C4D5CAE805A27E5BB866A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DFCEAF7C40494826A2118AF4E95C2C35 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prateek-portfolio'
          package: .
